### ISSUE TITLE
Windows 10 - svhdx filter driver installation error

### ISSUE THREAD

**Issue by gardart** [Microsoft/ws2016lab#120]
Thanks for a great deployment scripts, I have used the lab deployment scripts before and it works great!

At home I tried to run a copied version from a lab exercise and I get this error:

unable to load svhdx filter driver. Exiting Please use Server SKU or figure out how to install svhdx into the client SKU

any ideas on how I can install or should I get the SKU from the registry?

**Comment by jaromirk** [comment]
Hello Gardart. Please first vote here https://windowsserver.uservoice.com/forums/295056-storage/suggestions/32618456-add-shared-vhd-support-to-client-os ... **Following stuff is totally unsuported, and I'm sharing it just because you asked...** If you will do some research how to make this running, you will find there were people, who extracted deduplication from server using tools, that can extract cab. Similar way you can achieve to extract Failover Clustering feature, that will help you trust svhdxflt.sys (since trust is done using catalog as this driver is unsigned). Then you would install failover clustering cab using dism, then you would just copy svhdxflt into drivers and add it to registry to load. Then ws2016lab is able to detect svhdx is available and loads it. I guess I cannot share more because of EULA and I think someone would 🗡  me :). Ping me on email pls.
